#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises'
import { basename, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const UNSCOPED_ID = /^[A-Za-z][A-Za-z0-9._-]{0,63}$/u
const SCOPED_ID = /^(@[A-Za-z0-9._-]+\/)([A-Za-z][A-Za-z0-9._-]{0,63})$/u

export interface ScaffoldOptions {
  directory: string
  name: string
}

export function parseCreateArgs(argv: readonly string[]): ScaffoldOptions {
  const positional = argv.filter(arg => !arg.startsWith('-'))
  const raw = positional[0]
  if (raw === undefined || raw === '') {
    throw new Error('usage: create-fabric-plugin <name-or-directory>')
  }
  const scoped = SCOPED_ID.exec(raw)
  if (scoped !== null) {
    return { directory: resolve(scoped[2]!), name: raw }
  }
  const directory = resolve(raw)
  const name = basename(directory)
  if (!UNSCOPED_ID.test(name)) {
    throw new Error(`plugin name "${name}" is invalid; use a letter followed by letters, digits, ".", "_" or "-", optionally @scope/name`)
  }
  return { directory, name }
}

function runtimeId(packageName: string): string {
  return packageName.slice(packageName.lastIndexOf('/') + 1)
}

export function renderScaffold(name: string): Record<string, string> {
  const id = runtimeId(name)
  return {
    'package.json': `${JSON.stringify({
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      main: 'lib/index.js',
      exports: {
        '.': './lib/index.js',
        './client': './lib/client.js',
      },
      dsh: {
        bundle: { patch: './cordis.patch.yml' },
        client: {
          inject: ['@dsh-do/fabric'],
          platform: 'web',
        },
        dependencies: {
          '@dsh-do/fabric': '^0.6.0',
        },
      },
      scripts: {
        build: 'pnpm run typecheck && tsdown',
        typecheck: 'tsc --noEmit',
      },
      peerDependencies: {
        '@dsh-do/fabric': '^0.6.0',
        react: '^18.2.0',
      },
      devDependencies: {
        '@types/react': '~18.3.1',
        '@dsh-do/fabric': '^0.6.0',
        react: '^18.3.1',
        tsdown: '0.22.2',
        typescript: '~5.7.2',
      },
    }, null, 2)}\n`,
    'cordis.patch.yml': `- insert:\n    - id: ${id}\n      name: '${name}'\n`,
    'tsdown.config.ts': `import { defineConfig } from 'tsdown'\nimport { fabricPlugin } from '@dsh-do/fabric/build'\n\nexport default defineConfig(fabricPlugin({\n  id: '${name}',\n}))\n`,
    'tsconfig.json': `${JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        jsx: 'react-jsx',
        strict: true,
        exactOptionalPropertyTypes: true,
        skipLibCheck: true,
        noEmit: true,
        types: ['node'],
      },
      include: ['src'],
    }, null, 2)}\n`,
    'src/index.ts': `import { defineHostPlugin, mountHostPlugin } from '@dsh-do/fabric'\n\nconst definition = defineHostPlugin({\n  descriptor: {\n    name: '${name}',\n  },\n  setup() {\n    // Register typed Resources with context.resources.provide(...)\n  },\n})\n\nexport const { inject, apply } = mountHostPlugin(${JSON.stringify(name)}, '0.1.0', definition)\n`,
    'src/client/index.ts': `import { defineClientPlugin } from '@dsh-do/fabric/client'\nimport { Page, PageHeader } from '@dsh-do/fabric/ui'\n\nfunction HomePage() {\n  return (\n    <Page>\n      <PageHeader title="${name}" description="Generated by create-fabric-plugin." />\n    </Page>\n  )\n}\n\nexport default defineClientPlugin({\n  descriptor: {\n    name: '${name}',\n  },\n  setup(ctx) {\n    ctx.pages.define({\n      id: 'home',\n      label: '${name}',\n      view: HomePage,\n    })\n  },\n})\n`,
    'README.md': `# ${name}\n\nFabric 0.5 plugin generated by \`create-fabric-plugin\`.\n\nBusiness files use \`defineClientPlugin\` / \`defineHostPlugin\`. The build preset generates the DSH bootstrap and waits for the Fabric singleton.\n\n\`\`\`sh\npnpm install\npnpm build\ndsh plugin --profile web add "$(pwd)"\n\`\`\`\n`,
  }
}

export async function scaffoldPlugin(options: ScaffoldOptions): Promise<readonly string[]> {
  const files = renderScaffold(options.name)
  const written: string[] = []
  await mkdir(resolve(options.directory, 'src/client'), { recursive: true })
  for (const [relative, contents] of Object.entries(files)) {
    const path = resolve(options.directory, relative)
    await writeFile(path, contents, { flag: 'wx' })
    written.push(relative)
  }
  return written
}

async function main(): Promise<void> {
  const options = parseCreateArgs(process.argv.slice(2))
  const written = await scaffoldPlugin(options)
  process.stdout.write(`created ${options.name} in ${options.directory}\n${written.map(file => `  ${file}`).join('\n')}\n`)
}

const invoked = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href
if (invoked) {
  main().catch(error => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
    process.exitCode = 1
  })
}
