#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises'
import { basename, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const PLUGIN_ID = /^[A-Za-z][A-Za-z0-9._-]{0,63}$/u

export interface ScaffoldOptions {
  directory: string
  name: string
}

export function parseCreateArgs(argv: readonly string[]): ScaffoldOptions {
  const positional = argv.filter(arg => !arg.startsWith('-'))
  const raw = positional[0]
  if (raw === undefined || raw === '') {
    throw new Error('usage: create-fabric-plugin <name-or-directory>')
  }
  const directory = resolve(raw)
  const name = basename(directory)
  if (!PLUGIN_ID.test(name)) {
    throw new Error(`plugin name "${name}" is invalid; use a letter followed by letters, digits, ".", "_" or "-"`)
  }
  return { directory, name }
}

export function renderScaffold(name: string): Record<string, string> {
  return {
    'package.json': `${JSON.stringify({
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      main: 'lib/index.js',
      exports: {
        '.': './lib/index.js',
        './client': './lib/client.js',
      },
      dsh: {
        bundle: { patch: './cordis.patch.yml' },
        client: {
          inject: [
            '@deepseek-ai/dsh-client-runtime',
            '@deepseek-ai/dsh-client-ui-primitives',
            '@deepseek-ai/dsh-client-ui-slots',
            'fabric',
          ],
          platform: 'web',
        },
      },
      scripts: {
        build: 'pnpm run typecheck && tsdown',
        typecheck: 'tsc --noEmit',
      },
      peerDependencies: {
        '@deepseek-ai/dsh-client-runtime': '^0.1.0-rc.6',
        '@deepseek-ai/dsh-client-ui-primitives': '^0.1.0-rc.6',
        '@deepseek-ai/dsh-client-ui-slots': '^0.1.0-rc.6',
        fabric: '^0.4.0',
        react: '^18.2.0',
      },
      devDependencies: {
        '@deepseek-ai/dsh-client-runtime': '^0.1.0-rc.6',
        '@deepseek-ai/dsh-client-ui-primitives': '^0.1.0-rc.6',
        '@deepseek-ai/dsh-client-ui-slots': '^0.1.0-rc.6',
        '@types/react': '~18.3.1',
        fabric: '^0.4.0',
        react: '^18.3.1',
        tsdown: '0.22.2',
        typescript: '~5.7.2',
      },
    }, null, 2)}\n`,
    'cordis.patch.yml': `- insert:\n    - id: ${name}\n      name: '${name}'\n`,
    'tsdown.config.ts': `import { defineConfig } from 'tsdown'\nimport { fabricPlugin } from 'fabric/build'\n\nexport default defineConfig(fabricPlugin({\n  id: '${name}',\n}))\n`,
    'tsconfig.json': `${JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        jsx: 'react-jsx',
        strict: true,
        exactOptionalPropertyTypes: true,
        skipLibCheck: true,
        noEmit: true,
        types: ['node'],
      },
      include: ['src'],
    }, null, 2)}\n`,
    'src/index.ts': `import type { Context } from '@deepseek-ai/cordis'\n\n/** Host half. Add webServer routes here if the plugin needs persistence. */\nexport function apply(_ctx: Context): void {}\n`,
    'src/client/index.ts': `import type { ClientContext } from '@deepseek-ai/dsh-client-runtime/client'\nimport type { FabricPageProps } from 'fabric/client'\nimport { Page, PageHeader } from 'fabric/ui'\n\nexport const inject = ['fabric'] as const\n\nfunction HomePage(_props: FabricPageProps) {\n  return (\n    <Page>\n      <PageHeader title="${name}" description="Generated by create-fabric-plugin." />\n    </Page>\n  )\n}\n\nexport function apply(ctx: ClientContext): void {\n  ctx.fabric.register({\n    kind: 'mod',\n    id: '${name}',\n    name: '${name}',\n    version: '0.1.0',\n  })\n  ctx.fabric.register({\n    kind: 'page',\n    id: '${name}',\n    label: '${name}',\n    pluginId: '${name}',\n    component: HomePage,\n  })\n}\n`,
    'README.md': `# ${name}\n\nFabric plugin generated by \`create-fabric-plugin\`.\n\n\`\`\`sh\npnpm install\npnpm build\ndsh plugin --profile web add "$(pwd)"\n\`\`\`\n\nThe client entry **must** export \`inject = ['fabric']\` so Cordis waits for \`ctx.fabric\`.\n`,
  }
}

export async function scaffoldPlugin(options: ScaffoldOptions): Promise<readonly string[]> {
  const files = renderScaffold(options.name)
  const written: string[] = []
  await mkdir(resolve(options.directory, 'src/client'), { recursive: true })
  for (const [relative, contents] of Object.entries(files)) {
    const path = resolve(options.directory, relative)
    await writeFile(path, contents, { flag: 'wx' })
    written.push(relative)
  }
  return written
}

async function main(): Promise<void> {
  const options = parseCreateArgs(process.argv.slice(2))
  const written = await scaffoldPlugin(options)
  process.stdout.write(`created ${options.name} in ${options.directory}\n${written.map(file => `  ${file}`).join('\n')}\n`)
}

const invoked = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href
if (invoked) {
  main().catch(error => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
    process.exitCode = 1
  })
}
