#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises'
import { basename, resolve } from 'node:path'

const UNSCOPED_ID = /^[A-Za-z][A-Za-z0-9._-]{0,63}$/u
const SCOPED_ID = /^(@[A-Za-z0-9._-]+\/)([A-Za-z][A-Za-z0-9._-]{0,63})$/u

export interface ScaffoldOptions {
  directory: string
  name: string
}

export function parseCreateArgs(argv: readonly string[]): ScaffoldOptions {
  const positional = argv.filter(arg => !arg.startsWith('-'))
  const raw = positional[0]
  if (raw === undefined || raw === '') throw new Error('usage: create-fabric-plugin <name-or-directory>')
  const scoped = SCOPED_ID.exec(raw)
  if (scoped !== null) return { directory: resolve(scoped[2]!), name: raw }
  const directory = resolve(raw)
  const name = basename(directory)
  if (!UNSCOPED_ID.test(name)) {
    throw new Error(`plugin name "${name}" is invalid; use a letter followed by letters, digits, ".", "_" or "-", optionally @scope/name`)
  }
  return { directory, name }
}

export function renderScaffold(name: string): Record<string, string> {
  return {
    'package.json': `${JSON.stringify({
      name,
      version: '0.1.0',
      type: 'module',
      fabric: {
        format: 1,
        api: '^1.0.0',
        host: './lib/fabric-host.js',
        client: './lib/fabric-client.js',
      },
      files: ['lib'],
      scripts: {
        clean: 'node -e "require(\'node:fs\').rmSync(\'lib\',{recursive:true,force:true})"',
        build: 'pnpm run clean && pnpm run typecheck && fabric build',
        typecheck: 'tsc --noEmit',
        verify: 'fabric verify',
        pack: 'fabric pack',
        prepack: 'pnpm run build && pnpm run verify',
        prepublishOnly: 'pnpm run verify',
      },
      devDependencies: {
        '@dsh-do/fabric': '^1.0.0',
        '@types/node': '^22.20.0',
        '@types/react': '~18.3.1',
        '@types/react-dom': '~18.3.1',
        react: '^18.3.1',
        'react-dom': '^18.3.1',
        tsdown: '0.22.2',
        typescript: '~5.7.2',
      },
    }, null, 2)}\n`,
    'tsdown.config.ts': `import { defineConfig } from 'tsdown'\nimport { fabricRuntimePackage } from '@dsh-do/fabric/build'\n\nexport default defineConfig(fabricRuntimePackage())\n`,
    'tsconfig.json': `${JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        jsx: 'react-jsx',
        strict: true,
        exactOptionalPropertyTypes: true,
        skipLibCheck: true,
        noEmit: true,
        types: ['node'],
      },
      include: ['src'],
    }, null, 2)}\n`,
    'src/host.ts': `import { defineHostPlugin } from '@dsh-do/fabric/host'\n\nexport default defineHostPlugin({\n  descriptor: { name: '${name}' },\n  setup() {\n    // Register typed Resources with context.resources.provide(...).\n  },\n})\n`,
    'src/client/index.tsx': `import { defineClientPlugin, Page, PageHeader } from '@dsh-do/fabric/client'\n\nfunction HomePage() {\n  return (\n    <Page>\n      <PageHeader title="${name}" description="Fabric Runtime Package" />\n    </Page>\n  )\n}\n\nexport default defineClientPlugin({\n  descriptor: { name: '${name}' },\n  setup(ctx) {\n    ctx.pages.define({\n      id: 'home',\n      label: '${name}',\n      view: HomePage,\n      actions: [{\n        id: 'about',\n        label: 'About',\n        onClick: ({ dialogs }) => {\n          dialogs.open({ id: 'about', title: '${name}', content: 'Fabric Runtime Package' })\n        },\n      }],\n    })\n  },\n})\n`,
    'README.md': `# ${name}\n\nFabric Runtime Package generated by \`create-fabric-plugin\`.\n\n\`\`\`sh\npnpm install\npnpm build\npnpm verify\n# Install the built directory from Fabric Mods. No DSH restart is required.\n\`\`\`\n`,
  }
}

export async function scaffoldPlugin(options: ScaffoldOptions): Promise<readonly string[]> {
  const files = renderScaffold(options.name)
  const written: string[] = []
  await mkdir(resolve(options.directory, 'src/client'), { recursive: true })
  for (const [relative, contents] of Object.entries(files)) {
    const path = resolve(options.directory, relative)
    await writeFile(path, contents, { flag: 'wx' })
    written.push(relative)
  }
  return written
}

async function main(): Promise<void> {
  const options = parseCreateArgs(process.argv.slice(2))
  const written = await scaffoldPlugin(options)
  process.stdout.write(`created ${options.name} in ${options.directory}\n${written.map(file => `  ${file}`).join('\n')}\n`)
}

const invoked = process.argv[1] !== undefined && basename(process.argv[1]).toLowerCase() === 'create.js'
if (invoked) {
  main().catch(error => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
    process.exitCode = 1
  })
}
